name: Build
on:
  push:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: "Build with Gradle"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          path: "**/dclink-*/build/libs/*.jar"
