name: Build
on: [ push ]

jobs:
  build:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: "Build and Publish Api to Maven"
        uses: gradle/gradle-build-action@v2
        env:
          REPO_USERNAME: ${{ secrets.KALIMERO2_REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.KALIMERO2_REPO_SECRET }}
        with:
          arguments: publish
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          path: "**/claims-*/build/libs/*.jar"