name: Create Release

on:
  push:
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: "Publish with Gradle in Repository"
        uses: gradle/gradle-build-action@v3
        env:
          REPO_USERNAME: ${{ secrets.KALIMERO2_REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.KALIMERO2_REPO_SECRET }}
        with:
          arguments: build publish
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            "**/claims-paper/build/libs/claims-paper-*-all.jar"
            "**/claims-squaremap-integration/build/libs/claims-squaremap-integration-*.jar"
