name: Create Release

on:
  push:
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: "Publish with Gradle in Repository"
        uses: gradle/gradle-build-action@v2
        env:
          REPO_USERNAME: ${{ secrets.KALIMERO2_REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.KALIMERO2_REPO_SECRET }}
        with:
          arguments: build publish
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "**/dclink-*/build/libs/*.jar"
